name: Splendid CI/CD Pipeline

on:
  push:
    branches:
      - main # Triggers every time you push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./splendid-backend
          push: true
          tags: fhmnx/splendid-backend:latest

      - name: Inject Frontend Env Vars
        run: |
          echo "VITE_GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" > ./splendid-frontend/splendid/.env
          echo "VITE_WHATSAPP_NUMBER=94753837635" >> ./splendid-frontend/splendid/.env
          echo "VITE_PAYHERE_MERCHANT_ID=1228621" >> ./splendid-frontend/splendid/.env
          echo "VITE_PAYHERE_NOTIFY_URL=https://splendid-api.moonfleet.lk/api/payments/payhere/notify" >> ./splendid-frontend/splendid/.env
          echo "VITE_PAYHERE_RETURN_URL=https://splendid.moonfleet.lk/dashboard" >> ./splendid-frontend/splendid/.env
          echo "VITE_PAYHERE_CANCEL_URL=https://splendid.moonfleet.lk/packages" >> ./splendid-frontend/splendid/.env
          echo "VITE_API_URL=https://splendid-api.moonfleet.lk" >> ./splendid-frontend/splendid/.env

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./splendid-frontend/splendid
          push: true
          tags: fhmnx/splendid-frontend:latest

      - name: Copy docker-compose to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          source: "docker-compose.yml"
          target: "/www/server/panel/data/compose/splendid"

      - name: Deploy to Contabo VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Navigate to aaPanel's docker-compose folder for this project
            cd /www/server/panel/data/compose/splendid
            
            # Pull the fresh images and reboot the containers smoothly
            docker compose pull
            docker compose up -d